version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/pluralsight-docker-ci

    steps:
      - checkout

      - run: npm install
        
      # run tests!
      - run: mocha

