version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/pluralsight-docker-ci

    steps:
      - checkout

      - run: npm install
        
      # run tests!
      - run: npm test

  deploy: 
    steps:
      - run: $DOCKER_HUB_TRIGGER

workflows:
  version: 2
  build-and-deploy:
    jobs:
      docker: 
        - image: circleci/node:7.10
      - build
      # - deploy:
      #     requires: 
      #       -build

